### ISSUE TITLE
После входа в телегу scheduler не видит сессию

### ISSUE THREAD

**Issue by m0nclous** [m0nclous/click-claim-bot#30]
После того, как мы вошли в телегу (app контейнер) - scheduler контейнер всё еще не может слать запросы. Помогает рестарт

```
[ error ] 401: AUTH_KEY_UNREGISTERED (caused by contacts.ResolveUsername)
```

**Comment by serjikus22** [comment]
Проверить после слива редиса

**Comment by m0nclous** [comment]
Не актуально. Шедулера больше нет #51
