### ISSUE TITLE
Написать инструкцию развёртывания бота

### ISSUE THREAD

**Issue by m0nclous** [m0nclous/click-claim-bot#96]
Если кто-то нагуглил этот репозиторий - было бы приятно увидеть инструкцию по развёртыванию

**Comment by Inquisitor007** [comment]
Подскажите, как это все дело запустить?

**Comment by m0nclous** [comment]
@Inquisitor007 самое простое - docker-compose

Скачай из релиза click-claim-bot-slim.zip, там будет 2 файла и папка storage

.env.example переименуй в .env

.env заполни нужными данными
TELEGRAM_API_ID и TELEGRAM_API_HASH можно создать в https://my.telegram.org/auth

TELEGRAM_BOT_TOKEN и TELEGRAM_BOT_NAME можно получить https://t.me/BotFather

После этого запусти `docker-compose up -d`, управление ботом происходит через чат TELEGRAM_BOT_NAME

Скоро напишу подробную инструкцию, последняя версия бота развёрнута тут https://t.me/ClickClaimBot
